### ISSUE TITLE
nitpick: Can we switch the hex encoding of statusEntryId to multicodec or base64url encoding?

### ISSUE THREAD

**Issue by kdenhartog** [csuwildcat/status-trie#2]
Just a nitpick I noticed because I've been looking to make the ecosystem encodings a bit more consistent when ever possible.

**Comment by csuwildcat** [comment]
I believe it already says that in the text, though the value in the example might not reflect it.

**Comment by kdenhartog** [comment]
Sweet, I'll update that then. I haven't fully read through things yet it's just something I caught in the example and figured I'd drive by issue file it.
